/* V34 — Verb appendix with て / た / 辞書形 / ない + meanings. */
const V29_VERB_APPENDIX = [
  {
    "group": 1,
    "masu": "あいます",
    "te": "あって",
    "dictionary": "あう",
    "display": "あいます",
    "sourcePage": 191,
    "meaning": "gặp",
    "nai": "あわない",
    "ta": "あった"
  },
  {
    "group": 1,
    "masu": "あそびます",
    "te": "あそんで",
    "dictionary": "あそぶ",
    "display": "あそびます",
    "sourcePage": 191,
    "meaning": "chơi",
    "nai": "あそばない",
    "ta": "あそんだ"
  },
  {
    "group": 1,
    "masu": "あらいます",
    "te": "あらって",
    "dictionary": "あらう",
    "display": "あらいます",
    "sourcePage": 191,
    "meaning": "rửa",
    "nai": "あらわない",
    "ta": "あらった"
  },
  {
    "group": 1,
    "masu": "あります",
    "te": "あって",
    "dictionary": "ある",
    "display": "あります",
    "sourcePage": 191,
    "meaning": "có, ở (đồ vật/sự vật)",
    "nai": "ない",
    "ta": "あった"
  },
  {
    "group": 1,
    "masu": "あるきます",
    "te": "あるいて",
    "dictionary": "あるく",
    "display": "あるきます",
    "sourcePage": 191,
    "meaning": "đi bộ",
    "nai": "あるかない",
    "ta": "あるいた"
  },
  {
    "group": 1,
    "masu": "いいます",
    "te": "いって",
    "dictionary": "いう",
    "display": "いいます",
    "sourcePage": 191,
    "meaning": "nói",
    "nai": "いわない",
    "ta": "いった"
  },
  {
    "group": 1,
    "masu": "いきます",
    "te": "いって",
    "dictionary": "いく",
    "display": "いきます",
    "sourcePage": 191,
    "meaning": "đi",
    "nai": "いかない",
    "ta": "いった"
  },
  {
    "group": 1,
    "masu": "いそぎます",
    "te": "いそいで",
    "dictionary": "いそぐ",
    "display": "いそぎます",
    "sourcePage": 191,
    "meaning": "vội, gấp",
    "nai": "いそがない",
    "ta": "いそいだ"
  },
  {
    "group": 1,
    "masu": "いります",
    "te": "いって",
    "dictionary": "いる",
    "display": "いります",
    "sourcePage": 191,
    "meaning": "cần",
    "nai": "いらない",
    "ta": "いった"
  },
  {
    "group": 1,
    "masu": "うごきます",
    "te": "うごいて",
    "dictionary": "うごく",
    "display": "うごきます",
    "sourcePage": 191,
    "meaning": "chuyển động, chạy",
    "nai": "うごかない",
    "ta": "うごいた"
  },
  {
    "group": 1,
    "masu": "うたいます",
    "te": "うたって",
    "dictionary": "うたう",
    "display": "うたいます",
    "sourcePage": 191,
    "meaning": "hát",
    "nai": "うたわない",
    "ta": "うたった"
  },
  {
    "group": 1,
    "masu": "うります",
    "te": "うって",
    "dictionary": "うる",
    "display": "うります",
    "sourcePage": 191,
    "meaning": "bán",
    "nai": "うらない",
    "ta": "うった"
  },
  {
    "group": 1,
    "masu": "おきます",
    "te": "おいて",
    "dictionary": "おく",
    "display": "おきます",
    "sourcePage": 191,
    "meaning": "đặt, để",
    "nai": "おかない",
    "ta": "おいた"
  },
  {
    "group": 1,
    "masu": "おくります",
    "te": "おくって",
    "dictionary": "おくる",
    "display": "おくります",
    "sourcePage": 191,
    "meaning": "gửi",
    "nai": "おくらない",
    "ta": "おくった"
  },
  {
    "group": 1,
    "masu": "おします",
    "te": "おして",
    "dictionary": "おす",
    "display": "おします",
    "sourcePage": 191,
    "meaning": "bấm, ấn",
    "nai": "おさない",
    "ta": "おした"
  },
  {
    "group": 1,
    "masu": "おもいだします",
    "te": "おもいだして",
    "dictionary": "おもいだす",
    "display": "おもいだします",
    "sourcePage": 191,
    "meaning": "nhớ lại, hồi tưởng lại",
    "nai": "おもいださない",
    "ta": "おもいだした"
  },
  {
    "group": 1,
    "masu": "おもいます",
    "te": "おもって",
    "dictionary": "おもう",
    "display": "おもいます",
    "sourcePage": 191,
    "meaning": "nghĩ",
    "nai": "おもわない",
    "ta": "おもった"
  },
  {
    "group": 1,
    "masu": "およぎます",
    "te": "およいで",
    "dictionary": "およぐ",
    "display": "およぎます",
    "sourcePage": 191,
    "meaning": "bơi",
    "nai": "およがない",
    "ta": "およいだ"
  },
  {
    "group": 1,
    "masu": "おろします",
    "te": "おろして",
    "dictionary": "おろす",
    "display": "おろします",
    "sourcePage": 191,
    "meaning": "rút (tiền), lấy xuống",
    "nai": "おろさない",
    "ta": "おろした"
  },
  {
    "group": 1,
    "masu": "おわります",
    "te": "おわって",
    "dictionary": "おわる",
    "display": "おわります",
    "sourcePage": 191,
    "meaning": "hết, kết thúc, xong",
    "nai": "おわらない",
    "ta": "おわった"
  },
  {
    "group": 1,
    "masu": "かいます",
    "te": "かって",
    "dictionary": "かう",
    "display": "かいます",
    "sourcePage": 191,
    "meaning": "mua",
    "nai": "かわない",
    "ta": "かった"
  },
  {
    "group": 1,
    "masu": "かえします",
    "te": "かえして",
    "dictionary": "かえす",
    "display": "かえします",
    "sourcePage": 191,
    "meaning": "trả lại",
    "nai": "かえさない",
    "ta": "かえした"
  },
  {
    "group": 1,
    "masu": "かえります",
    "te": "かえって",
    "dictionary": "かえる",
    "display": "かえります",
    "sourcePage": 191,
    "meaning": "về",
    "nai": "かえらない",
    "ta": "かえった"
  },
  {
    "group": 1,
    "masu": "かかります",
    "te": "かかって",
    "dictionary": "かかる",
    "display": "かかります",
    "sourcePage": 191,
    "meaning": "mất, tốn (thời gian, tiền bạc)",
    "nai": "かからない",
    "ta": "かかった"
  },
  {
    "group": 1,
    "masu": "かきます",
    "te": "かいて",
    "dictionary": "かく",
    "display": "かきます",
    "sourcePage": 191,
    "meaning": "viết (cũng có nghĩa là vẽ; khi mang nghĩa vẽ sách dùng Hiragana)",
    "nai": "かかない",
    "ta": "かいた"
  },
  {
    "group": 1,
    "masu": "かします",
    "te": "かして",
    "dictionary": "かす",
    "display": "かします",
    "sourcePage": 191,
    "meaning": "cho mượn, cho vay",
    "nai": "かさない",
    "ta": "かした"
  },
  {
    "group": 1,
    "masu": "かちます",
    "te": "かって",
    "dictionary": "かつ",
    "display": "かちます",
    "sourcePage": 191,
    "meaning": "thắng",
    "nai": "かたない",
    "ta": "かった"
  },
  {
    "group": 1,
    "masu": "かぶります",
    "te": "かぶって",
    "dictionary": "かぶる",
    "display": "かぶります",
    "sourcePage": 191,
    "meaning": "đội (mũ, v.v.)",
    "nai": "かぶらない",
    "ta": "かぶった"
  },
  {
    "group": 1,
    "masu": "がんばります",
    "te": "がんばって",
    "dictionary": "がんばる",
    "display": "がんばります",
    "sourcePage": 191,
    "meaning": "cố, cố gắng",
    "nai": "がんばらない",
    "ta": "がんばった"
  },
  {
    "group": 1,
    "masu": "ききます",
    "te": "きいて",
    "dictionary": "きく",
    "display": "ききます",
    "sourcePage": 193,
    "meaning": "nghe",
    "nai": "きかない",
    "ta": "きいた"
  },
  {
    "group": 1,
    "masu": "きります",
    "te": "きって",
    "dictionary": "きる",
    "display": "きります",
    "sourcePage": 193,
    "meaning": "cắt",
    "nai": "きらない",
    "ta": "きった"
  },
  {
    "group": 1,
    "masu": "けします",
    "te": "けして",
    "dictionary": "けす",
    "display": "けします",
    "sourcePage": 193,
    "meaning": "tắt",
    "nai": "けさない",
    "ta": "けした"
  },
  {
    "group": 1,
    "masu": "さわります",
    "te": "さわって",
    "dictionary": "さわる",
    "display": "さわります",
    "sourcePage": 193,
    "meaning": "sờ, chạm",
    "nai": "さわらない",
    "ta": "さわった"
  },
  {
    "group": 1,
    "masu": "しります",
    "te": "しって",
    "dictionary": "しる",
    "display": "しります",
    "sourcePage": 193,
    "meaning": "biết",
    "nai": "しらない",
    "ta": "しった"
  },
  {
    "group": 1,
    "masu": "すいます",
    "te": "すって",
    "dictionary": "すう",
    "display": "すいます",
    "sourcePage": 193,
    "meaning": "hút",
    "nai": "すわない",
    "ta": "すった"
  },
  {
    "group": 1,
    "masu": "すみます",
    "te": "すんで",
    "dictionary": "すむ",
    "display": "すみます",
    "sourcePage": 193,
    "meaning": "sống, ở",
    "nai": "すまない",
    "ta": "すんだ"
  },
  {
    "group": 1,
    "masu": "すわります",
    "te": "すわって",
    "dictionary": "すわる",
    "display": "すわります",
    "sourcePage": 193,
    "meaning": "ngồi",
    "nai": "すわらない",
    "ta": "すわった"
  },
  {
    "group": 1,
    "masu": "だします",
    "te": "だして",
    "dictionary": "だす",
    "display": "だします",
    "sourcePage": 193,
    "meaning": "lấy ra, đưa ra, gửi",
    "nai": "ださない",
    "ta": "だした"
  },
  {
    "group": 1,
    "masu": "たちます",
    "te": "たって",
    "dictionary": "たつ",
    "display": "たちます",
    "sourcePage": 193,
    "meaning": "đứng",
    "nai": "たたない",
    "ta": "たった"
  },
  {
    "group": 1,
    "masu": "つかいます",
    "te": "つかって",
    "dictionary": "つかう",
    "display": "つかいます",
    "sourcePage": 193,
    "meaning": "dùng, sử dụng",
    "nai": "つかわない",
    "ta": "つかった"
  },
  {
    "group": 1,
    "masu": "つきます",
    "te": "ついて",
    "dictionary": "つく",
    "display": "つきます",
    "sourcePage": 193,
    "meaning": "đến",
    "nai": "つかない",
    "ta": "ついた"
  },
  {
    "group": 1,
    "masu": "つくります",
    "te": "つくって",
    "dictionary": "つくる",
    "display": "つくります",
    "sourcePage": 193,
    "meaning": "làm, chế tạo, sản xuất",
    "nai": "つくらない",
    "ta": "つくった"
  },
  {
    "group": 1,
    "masu": "つれていきます",
    "te": "つれていって",
    "dictionary": "つれていく",
    "display": "つれていきます",
    "sourcePage": 193,
    "meaning": "dẫn (một ai đó) đi",
    "nai": "つれていかない",
    "ta": "つれていった"
  },
  {
    "group": 1,
    "masu": "てつだいます",
    "te": "てつだって",
    "dictionary": "てつだう",
    "display": "てつだいます",
    "sourcePage": 193,
    "meaning": "giúp (làm việc gì)",
    "nai": "てつだわない",
    "ta": "てつだった"
  },
  {
    "group": 1,
    "masu": "とまります",
    "te": "とまって",
    "dictionary": "とまる",
    "display": "とまります",
    "sourcePage": 193,
    "meaning": "dừng, đỗ",
    "nai": "とまらない",
    "ta": "とまった"
  },
  {
    "group": 1,
    "masu": "とります",
    "te": "とって",
    "dictionary": "とる",
    "display": "とります",
    "sourcePage": 193,
    "meaning": "lấy, chuyển",
    "nai": "とらない",
    "ta": "とった"
  },
  {
    "group": 1,
    "masu": "なおします",
    "te": "なおして",
    "dictionary": "なおす",
    "display": "なおします",
    "sourcePage": 193,
    "meaning": "chữa, sửa",
    "nai": "なおさない",
    "ta": "なおした"
  },
  {
    "group": 1,
    "masu": "なくします",
    "te": "なくして",
    "dictionary": "なくす",
    "display": "なくします",
    "sourcePage": 193,
    "meaning": "làm mất, đánh mất",
    "nai": "なくさない",
    "ta": "なくした"
  },
  {
    "group": 1,
    "masu": "ならいます",
    "te": "ならって",
    "dictionary": "ならう",
    "display": "ならいます",
    "sourcePage": 193,
    "meaning": "học, tập",
    "nai": "ならわない",
    "ta": "ならった"
  },
  {
    "group": 1,
    "masu": "なります",
    "te": "なって",
    "dictionary": "なる",
    "display": "なります",
    "sourcePage": 193,
    "meaning": "trở thành, trở nên",
    "nai": "ならない",
    "ta": "なった"
  },
  {
    "group": 1,
    "masu": "ぬぎます",
    "te": "ぬいで",
    "dictionary": "ぬぐ",
    "display": "ぬぎます",
    "sourcePage": 193,
    "meaning": "cởi (quần áo, giày, v.v.)",
    "nai": "ぬがない",
    "ta": "ぬいだ"
  },
  {
    "group": 1,
    "masu": "のぼります",
    "te": "のぼって",
    "dictionary": "のぼる",
    "display": "のぼります",
    "sourcePage": 193,
    "meaning": "leo (núi), lên",
    "nai": "のぼらない",
    "ta": "のぼった"
  },
  {
    "group": 1,
    "masu": "のみます",
    "te": "のんで",
    "dictionary": "のむ",
    "display": "のみます",
    "sourcePage": 193,
    "meaning": "uống",
    "nai": "のまない",
    "ta": "のんだ"
  },
  {
    "group": 1,
    "masu": "のります",
    "te": "のって",
    "dictionary": "のる",
    "display": "のります",
    "sourcePage": 193,
    "meaning": "lên, đi (phương tiện)",
    "nai": "のらない",
    "ta": "のった"
  },
  {
    "group": 1,
    "masu": "はいります",
    "te": "はいって",
    "dictionary": "はいる",
    "display": "はいります",
    "sourcePage": 193,
    "meaning": "vào",
    "nai": "はいらない",
    "ta": "はいった"
  },
  {
    "group": 1,
    "masu": "はきます",
    "te": "はいて",
    "dictionary": "はく",
    "display": "はきます",
    "sourcePage": 193,
    "meaning": "đi, mặc (giày, quần âu, v.v.)",
    "nai": "はかない",
    "ta": "はいた"
  },
  {
    "group": 1,
    "masu": "はたらきます",
    "te": "はたらいて",
    "dictionary": "はたらく",
    "display": "はたらきます",
    "sourcePage": 195,
    "meaning": "làm việc",
    "nai": "はたらかない",
    "ta": "はたらいた"
  },
  {
    "group": 1,
    "masu": "はなします",
    "te": "はなして",
    "dictionary": "はなす",
    "display": "はなします",
    "sourcePage": 195,
    "meaning": "nói, nói chuyện",
    "nai": "はなさない",
    "ta": "はなした"
  },
  {
    "group": 1,
    "masu": "はらいます",
    "te": "はらって",
    "dictionary": "はらう",
    "display": "はらいます",
    "sourcePage": 195,
    "meaning": "trả tiền",
    "nai": "はらわない",
    "ta": "はらった"
  },
  {
    "group": 1,
    "masu": "ひきます",
    "te": "ひいて",
    "dictionary": "ひく",
    "display": "ひきます",
    "sourcePage": 195,
    "meaning": "kéo",
    "nai": "ひかない",
    "ta": "ひいた"
  },
  {
    "group": 1,
    "masu": "ふります",
    "te": "ふって",
    "dictionary": "ふる",
    "display": "ふります",
    "sourcePage": 195,
    "meaning": "mưa",
    "nai": "ふらない",
    "ta": "ふった"
  },
  {
    "group": 1,
    "masu": "まがります",
    "te": "まがって",
    "dictionary": "まがる",
    "display": "まがります",
    "sourcePage": 195,
    "meaning": "rẽ",
    "nai": "まがらない",
    "ta": "まがった"
  },
  {
    "group": 1,
    "masu": "まちます",
    "te": "まって",
    "dictionary": "まつ",
    "display": "まちます",
    "sourcePage": 195,
    "meaning": "đợi, chờ",
    "nai": "またない",
    "ta": "まった"
  },
  {
    "group": 1,
    "masu": "まわします",
    "te": "まわして",
    "dictionary": "まわす",
    "display": "まわします",
    "sourcePage": 195,
    "meaning": "vặn",
    "nai": "まわさない",
    "ta": "まわした"
  },
  {
    "group": 1,
    "masu": "もちます",
    "te": "もって",
    "dictionary": "もつ",
    "display": "もちます",
    "sourcePage": 195,
    "meaning": "mang, cầm",
    "nai": "もたない",
    "ta": "もった"
  },
  {
    "group": 1,
    "masu": "もっていきます",
    "te": "もっていって",
    "dictionary": "もっていく",
    "display": "もっていきます",
    "sourcePage": 195,
    "meaning": "mang đi, mang theo",
    "nai": "もっていかない",
    "ta": "もっていった"
  },
  {
    "group": 1,
    "masu": "もらいます",
    "te": "もらって",
    "dictionary": "もらう",
    "display": "もらいます",
    "sourcePage": 195,
    "meaning": "nhận",
    "nai": "もらわない",
    "ta": "もらった"
  },
  {
    "group": 1,
    "masu": "やくにたちます",
    "te": "やくにたって",
    "dictionary": "やくにたつ",
    "display": "やくにたちます",
    "sourcePage": 195,
    "meaning": "hữu ích, giúp ích",
    "nai": "やくにたたない",
    "ta": "やくにたった"
  },
  {
    "group": 1,
    "masu": "やすみます",
    "te": "やすんで",
    "dictionary": "やすむ",
    "display": "やすみます",
    "sourcePage": 195,
    "meaning": "nghỉ, nghỉ ngơi",
    "nai": "やすまない",
    "ta": "やすんだ"
  },
  {
    "group": 1,
    "masu": "よびます",
    "te": "よんで",
    "dictionary": "よぶ",
    "display": "よびます",
    "sourcePage": 195,
    "meaning": "gọi",
    "nai": "よばない",
    "ta": "よんだ"
  },
  {
    "group": 1,
    "masu": "よみます",
    "te": "よんで",
    "dictionary": "よむ",
    "display": "よみます",
    "sourcePage": 195,
    "meaning": "đọc",
    "nai": "よまない",
    "ta": "よんだ"
  },
  {
    "group": 1,
    "masu": "わかります",
    "te": "わかって",
    "dictionary": "わかる",
    "display": "わかります",
    "sourcePage": 195,
    "meaning": "hiểu",
    "nai": "わからない",
    "ta": "わかった"
  },
  {
    "group": 1,
    "masu": "わたります",
    "te": "わたって",
    "dictionary": "わたる",
    "display": "わたります",
    "sourcePage": 195,
    "meaning": "băng qua",
    "nai": "わたらない",
    "ta": "わたった"
  },
  {
    "group": 2,
    "masu": "あけます",
    "te": "あけて",
    "dictionary": "あける",
    "display": "あけます",
    "sourcePage": 197,
    "meaning": "mở",
    "nai": "あけない",
    "ta": "あけた"
  },
  {
    "group": 2,
    "masu": "あげます",
    "te": "あげて",
    "dictionary": "あげる",
    "display": "あげます",
    "sourcePage": 197,
    "meaning": "cho, tặng",
    "nai": "あげない",
    "ta": "あげた"
  },
  {
    "group": 2,
    "masu": "あつめます",
    "te": "あつめて",
    "dictionary": "あつめる",
    "display": "あつめます",
    "sourcePage": 197,
    "meaning": "sưu tầm, thu thập, tập hợp",
    "nai": "あつめない",
    "ta": "あつめた"
  },
  {
    "group": 2,
    "masu": "あびます",
    "te": "あびて",
    "dictionary": "あびる",
    "display": "あびます",
    "sourcePage": 197,
    "meaning": "tắm",
    "nai": "あびない",
    "ta": "あびた"
  },
  {
    "group": 2,
    "masu": "います",
    "te": "いて",
    "dictionary": "いる",
    "display": "います",
    "sourcePage": 197,
    "meaning": "có, ở (người/động vật)",
    "nai": "いない",
    "ta": "いた"
  },
  {
    "group": 2,
    "masu": "いれます",
    "te": "いれて",
    "dictionary": "いれる",
    "display": "いれます",
    "sourcePage": 197,
    "meaning": "cho vào, bỏ vào",
    "nai": "いれない",
    "ta": "いれた"
  },
  {
    "group": 2,
    "masu": "うまれます",
    "te": "うまれて",
    "dictionary": "うまれる",
    "display": "うまれます",
    "sourcePage": 197,
    "meaning": "sinh ra",
    "nai": "うまれない",
    "ta": "うまれた"
  },
  {
    "group": 2,
    "masu": "おきます",
    "te": "おきて",
    "dictionary": "おきる",
    "display": "おきます",
    "sourcePage": 197,
    "meaning": "thức dậy",
    "nai": "おきない",
    "ta": "おきた"
  },
  {
    "group": 2,
    "masu": "おしえます",
    "te": "おしえて",
    "dictionary": "おしえる",
    "display": "おしえます",
    "sourcePage": 197,
    "meaning": "dạy",
    "nai": "おしえない",
    "ta": "おしえた"
  },
  {
    "group": 2,
    "masu": "おぼえます",
    "te": "おぼえて",
    "dictionary": "おぼえる",
    "display": "おぼえます",
    "sourcePage": 197,
    "meaning": "nhớ",
    "nai": "おぼえない",
    "ta": "おぼえた"
  },
  {
    "group": 2,
    "masu": "おります",
    "te": "おりて",
    "dictionary": "おりる",
    "display": "おります",
    "sourcePage": 197,
    "meaning": "xuống (tàu, xe)",
    "nai": "おりない",
    "ta": "おりた"
  },
  {
    "group": 2,
    "masu": "かえます",
    "te": "かえて",
    "dictionary": "かえる",
    "display": "かえます",
    "sourcePage": 197,
    "meaning": "đổi",
    "nai": "かえない",
    "ta": "かえた"
  },
  {
    "group": 2,
    "masu": "かけます",
    "te": "かけて",
    "dictionary": "かける",
    "display": "かけます",
    "sourcePage": 197,
    "meaning": "gọi (điện thoại), đeo",
    "nai": "かけない",
    "ta": "かけた"
  },
  {
    "group": 2,
    "masu": "かります",
    "te": "かりて",
    "dictionary": "かりる",
    "display": "かります",
    "sourcePage": 197,
    "meaning": "mượn, vay",
    "nai": "かりない",
    "ta": "かりた"
  },
  {
    "group": 2,
    "masu": "かんがえます",
    "te": "かんがえて",
    "dictionary": "かんがえる",
    "display": "かんがえます",
    "sourcePage": 197,
    "meaning": "nghĩ, suy nghĩ",
    "nai": "かんがえない",
    "ta": "かんがえた"
  },
  {
    "group": 2,
    "masu": "きます",
    "te": "きて",
    "dictionary": "きる",
    "display": "着ます（きます）",
    "sourcePage": 197,
    "meaning": "mặc (áo sơ mi, v.v.)",
    "nai": "きない",
    "ta": "きた"
  },
  {
    "group": 2,
    "masu": "きをつけます",
    "te": "きをつけて",
    "dictionary": "きをつける",
    "display": "きをつけます",
    "sourcePage": 197,
    "meaning": "chú ý, bảo trọng",
    "nai": "きをつけない",
    "ta": "きをつけた"
  },
  {
    "group": 2,
    "masu": "くれます",
    "te": "くれて",
    "dictionary": "くれる",
    "display": "くれます",
    "sourcePage": 197,
    "meaning": "cho, tặng (tôi)",
    "nai": "くれない",
    "ta": "くれた"
  },
  {
    "group": 2,
    "masu": "しめます",
    "te": "しめて",
    "dictionary": "しめる",
    "display": "しめます",
    "sourcePage": 197,
    "meaning": "đóng (cửa, cửa sổ)",
    "nai": "しめない",
    "ta": "しめた"
  },
  {
    "group": 2,
    "masu": "しらべます",
    "te": "しらべて",
    "dictionary": "しらべる",
    "display": "しらべます",
    "sourcePage": 197,
    "meaning": "tìm hiểu, kiểm tra, điều tra",
    "nai": "しらべない",
    "ta": "しらべた"
  },
  {
    "group": 2,
    "masu": "すてます",
    "te": "すてて",
    "dictionary": "すてる",
    "display": "すてます",
    "sourcePage": 197,
    "meaning": "vứt, bỏ, bỏ đi",
    "nai": "すてない",
    "ta": "すてた"
  },
  {
    "group": 2,
    "masu": "たべます",
    "te": "たべて",
    "dictionary": "たべる",
    "display": "たべます",
    "sourcePage": 197,
    "meaning": "ăn",
    "nai": "たべない",
    "ta": "たべた"
  },
  {
    "group": 2,
    "masu": "たります",
    "te": "たりて",
    "dictionary": "たりる",
    "display": "たります",
    "sourcePage": 197,
    "meaning": "đủ",
    "nai": "たりない",
    "ta": "たりた"
  },
  {
    "group": 2,
    "masu": "つかれます",
    "te": "つかれて",
    "dictionary": "つかれる",
    "display": "つかれます",
    "sourcePage": 197,
    "meaning": "mệt",
    "nai": "つかれない",
    "ta": "つかれた"
  },
  {
    "group": 2,
    "masu": "つけます",
    "te": "つけて",
    "dictionary": "つける",
    "display": "つけます",
    "sourcePage": 197,
    "meaning": "bật",
    "nai": "つけない",
    "ta": "つけた"
  },
  {
    "group": 2,
    "masu": "でかけます",
    "te": "でかけて",
    "dictionary": "でかける",
    "display": "でかけます",
    "sourcePage": 197,
    "meaning": "ra ngoài",
    "nai": "でかけない",
    "ta": "でかけた"
  },
  {
    "group": 2,
    "masu": "できます",
    "te": "できて",
    "dictionary": "できる",
    "display": "できます",
    "sourcePage": 197,
    "meaning": "có thể, làm được",
    "nai": "できない",
    "ta": "できた"
  },
  {
    "group": 2,
    "masu": "でます",
    "te": "でて",
    "dictionary": "でる",
    "display": "でます",
    "sourcePage": 197,
    "meaning": "ra",
    "nai": "でない",
    "ta": "でた"
  },
  {
    "group": 2,
    "masu": "とめます",
    "te": "とめて",
    "dictionary": "とめる",
    "display": "とめます",
    "sourcePage": 199,
    "meaning": "dừng, đỗ",
    "nai": "とめない",
    "ta": "とめた"
  },
  {
    "group": 2,
    "masu": "ねます",
    "te": "ねて",
    "dictionary": "ねる",
    "display": "ねます",
    "sourcePage": 199,
    "meaning": "ngủ, đi ngủ",
    "nai": "ねない",
    "ta": "ねた"
  },
  {
    "group": 2,
    "masu": "のりかえます",
    "te": "のりかえて",
    "dictionary": "のりかえる",
    "display": "のりかえます",
    "sourcePage": 199,
    "meaning": "chuyển, đổi (tàu)",
    "nai": "のりかえない",
    "ta": "のりかえた"
  },
  {
    "group": 2,
    "masu": "はじめます",
    "te": "はじめて",
    "dictionary": "はじめる",
    "display": "はじめます",
    "sourcePage": 199,
    "meaning": "bắt đầu",
    "nai": "はじめない",
    "ta": "はじめた"
  },
  {
    "group": 2,
    "masu": "まけます",
    "te": "まけて",
    "dictionary": "まける",
    "display": "まけます",
    "sourcePage": 199,
    "meaning": "thua",
    "nai": "まけない",
    "ta": "まけた"
  },
  {
    "group": 2,
    "masu": "みせます",
    "te": "みせて",
    "dictionary": "みせる",
    "display": "みせます",
    "sourcePage": 199,
    "meaning": "cho xem, trình",
    "nai": "みせない",
    "ta": "みせた"
  },
  {
    "group": 2,
    "masu": "みます",
    "te": "みて",
    "dictionary": "みる",
    "display": "みます",
    "sourcePage": 199,
    "meaning": "nhìn, xem",
    "nai": "みない",
    "ta": "みた"
  },
  {
    "group": 2,
    "masu": "むかえます",
    "te": "むかえて",
    "dictionary": "むかえる",
    "display": "むかえます",
    "sourcePage": 199,
    "meaning": "đón",
    "nai": "むかえない",
    "ta": "むかえた"
  },
  {
    "group": 2,
    "masu": "やめます",
    "te": "やめて",
    "dictionary": "やめる",
    "display": "やめます",
    "sourcePage": 199,
    "meaning": "nghỉ, bỏ",
    "nai": "やめない",
    "ta": "やめた"
  },
  {
    "group": 2,
    "masu": "わすれます",
    "te": "わすれて",
    "dictionary": "わすれる",
    "display": "わすれます",
    "sourcePage": 199,
    "meaning": "quên",
    "nai": "わすれない",
    "ta": "わすれた"
  },
  {
    "group": 3,
    "masu": "あんないします",
    "te": "あんないして",
    "dictionary": "あんないする",
    "display": "あんないします",
    "sourcePage": 201,
    "meaning": "hướng dẫn, giới thiệu, dẫn đường",
    "nai": "あんないしない",
    "ta": "あんないした"
  },
  {
    "group": 3,
    "masu": "うんてんします",
    "te": "うんてんして",
    "dictionary": "うんてんする",
    "display": "うんてんします",
    "sourcePage": 201,
    "meaning": "lái",
    "nai": "うんてんしない",
    "ta": "うんてんした"
  },
  {
    "group": 3,
    "masu": "かいものします",
    "te": "かいものして",
    "dictionary": "かいものする",
    "display": "かいものします",
    "sourcePage": 201,
    "meaning": "mua sắm, mua hàng",
    "nai": "かいものしない",
    "ta": "かいものした"
  },
  {
    "group": 3,
    "masu": "きます",
    "te": "きて",
    "dictionary": "くる",
    "display": "来ます（きます）",
    "sourcePage": 201,
    "meaning": "đến",
    "nai": "こない",
    "ta": "きた"
  },
  {
    "group": 3,
    "masu": "けっこんします",
    "te": "けっこんして",
    "dictionary": "けっこんする",
    "display": "けっこんします",
    "sourcePage": 201,
    "meaning": "kết hôn, lập gia đình, cưới",
    "nai": "けっこんしない",
    "ta": "けっこんした"
  },
  {
    "group": 3,
    "masu": "けんがくします",
    "te": "けんがくして",
    "dictionary": "けんがくする",
    "display": "けんがくします",
    "sourcePage": 201,
    "meaning": "tham quan kiến tập",
    "nai": "けんがくしない",
    "ta": "けんがくした"
  },
  {
    "group": 3,
    "masu": "けんきゅうします",
    "te": "けんきゅうして",
    "dictionary": "けんきゅうする",
    "display": "けんきゅうします",
    "sourcePage": 201,
    "meaning": "nghiên cứu",
    "nai": "けんきゅうしない",
    "ta": "けんきゅうした"
  },
  {
    "group": 3,
    "masu": "コピーします",
    "te": "コピーして",
    "dictionary": "コピーする",
    "display": "コピーします",
    "sourcePage": 201,
    "meaning": "copy, phô-tô",
    "nai": "コピーしない",
    "ta": "コピーした"
  },
  {
    "group": 3,
    "masu": "さんぽします",
    "te": "さんぽして",
    "dictionary": "さんぽする",
    "display": "さんぽします",
    "sourcePage": 201,
    "meaning": "đi dạo",
    "nai": "さんぽしない",
    "ta": "さんぽした"
  },
  {
    "group": 3,
    "masu": "ざんぎょうします",
    "te": "ざんぎょうして",
    "dictionary": "ざんぎょうする",
    "display": "ざんぎょうします",
    "sourcePage": 201,
    "meaning": "làm thêm giờ",
    "nai": "ざんぎょうしない",
    "ta": "ざんぎょうした"
  },
  {
    "group": 3,
    "masu": "します",
    "te": "して",
    "dictionary": "する",
    "display": "します",
    "sourcePage": 201,
    "meaning": "làm, chơi",
    "nai": "しない",
    "ta": "した"
  },
  {
    "group": 3,
    "masu": "しゅうりします",
    "te": "しゅうりして",
    "dictionary": "しゅうりする",
    "display": "しゅうりします",
    "sourcePage": 201,
    "meaning": "sửa chữa, tu sửa",
    "nai": "しゅうりしない",
    "ta": "しゅうりした"
  },
  {
    "group": 3,
    "masu": "しゅっちょうします",
    "te": "しゅっちょうして",
    "dictionary": "しゅっちょうする",
    "display": "しゅっちょうします",
    "sourcePage": 201,
    "meaning": "đi công tác",
    "nai": "しゅっちょうしない",
    "ta": "しゅっちょうした"
  },
  {
    "group": 3,
    "masu": "しょうかいします",
    "te": "しょうかいして",
    "dictionary": "しょうかいする",
    "display": "しょうかいします",
    "sourcePage": 201,
    "meaning": "giới thiệu",
    "nai": "しょうかいしない",
    "ta": "しょうかいした"
  },
  {
    "group": 3,
    "masu": "しょくじします",
    "te": "しょくじして",
    "dictionary": "しょくじする",
    "display": "しょくじします",
    "sourcePage": 201,
    "meaning": "ăn cơm, dùng bữa",
    "nai": "しょくじしない",
    "ta": "しょくじした"
  },
  {
    "group": 3,
    "masu": "しんぱいします",
    "te": "しんぱいして",
    "dictionary": "しんぱいする",
    "display": "しんぱいします",
    "sourcePage": 201,
    "meaning": "lo lắng",
    "nai": "しんぱいしない",
    "ta": "しんぱいした"
  },
  {
    "group": 3,
    "masu": "せつめいします",
    "te": "せつめいして",
    "dictionary": "せつめいする",
    "display": "せつめいします",
    "sourcePage": 201,
    "meaning": "giải thích, trình bày",
    "nai": "せつめいしない",
    "ta": "せつめいした"
  },
  {
    "group": 3,
    "masu": "せんたくします",
    "te": "せんたくして",
    "dictionary": "せんたくする",
    "display": "せんたくします",
    "sourcePage": 201,
    "meaning": "giặt (quần áo)",
    "nai": "せんたくしない",
    "ta": "せんたくした"
  },
  {
    "group": 3,
    "masu": "そうじします",
    "te": "そうじして",
    "dictionary": "そうじする",
    "display": "そうじします",
    "sourcePage": 201,
    "meaning": "dọn vệ sinh (căn phòng)",
    "nai": "そうじしない",
    "ta": "そうじした"
  },
  {
    "group": 3,
    "masu": "つれてきます",
    "te": "つれてきて",
    "dictionary": "つれてくる",
    "display": "つれてきます",
    "sourcePage": 201,
    "meaning": "dẫn (một ai đó) đến",
    "nai": "つれてこない",
    "ta": "つれてきた"
  },
  {
    "group": 3,
    "masu": "でんわします",
    "te": "でんわして",
    "dictionary": "でんわする",
    "display": "でんわします",
    "sourcePage": 201,
    "meaning": "gọi điện thoại",
    "nai": "でんわしない",
    "ta": "でんわした"
  },
  {
    "group": 3,
    "masu": "べんきょうします",
    "te": "べんきょうして",
    "dictionary": "べんきょうする",
    "display": "べんきょうします",
    "sourcePage": 201,
    "meaning": "học",
    "nai": "べんきょうしない",
    "ta": "べんきょうした"
  },
  {
    "group": 3,
    "masu": "もってきます",
    "te": "もってきて",
    "dictionary": "もってくる",
    "display": "もってきます",
    "sourcePage": 201,
    "meaning": "mang đến",
    "nai": "もってこない",
    "ta": "もってきた"
  },
  {
    "group": 3,
    "masu": "よやくします",
    "te": "よやくして",
    "dictionary": "よやくする",
    "display": "よやくします",
    "sourcePage": 201,
    "meaning": "đặt chỗ, đặt trước",
    "nai": "よやくしない",
    "ta": "よやくした"
  },
  {
    "group": 3,
    "masu": "りゅうがくします",
    "te": "りゅうがくして",
    "dictionary": "りゅうがくする",
    "display": "りゅうがくします",
    "sourcePage": 201,
    "meaning": "du học",
    "nai": "りゅうがくしない",
    "ta": "りゅうがくした"
  }
];
