/* ==========================================================
   V35 — RANDOM JAPANESE -> VIETNAMESE FLASHCARDS • LESSONS 1–50
   Front: Japanese Kana only
   Back: Vietnamese meaning + optional Kanji
   ========================================================== */
let v35JpViState=null;
function v35Lesson(id){id=+id;if(id<=25){const l=LESSONS[id-1];return {id,level:'N5',vocab:l.vocab};}const l=n4mLesson(id);return {id,level:'N4',vocab:l.vocab};}
function v35Kana(v){return String(v.kana||v.jp||'').trim();}
function v35InjectPracticeCard(){const grid=document.querySelector('.mode-grid');if(!grid||grid.querySelector('.v35-jpvi-practice-card'))return;const card=document.createElement('button');card.className='mode-card v35-jpvi-practice-card';card.onclick=openV35JpViFlash;card.innerHTML=`<h3>🇯🇵 Flash Nhật → Việt</h3><p>Random từ vựng theo Bài 1–50: nhìn Kana tiếng Nhật rồi tự nhớ nghĩa tiếng Việt.</p><small>Chọn nhiều bài • Quên/Nhớ • ôn lại thẻ quên</small>`;grid.appendChild(card);}
const _v35OpenPractice=openPractice;
openPractice=function(){const r=_v35OpenPractice();setTimeout(v35InjectPracticeCard,0);return r;};
function v35Range(a,b){return [...Array(b-a+1)].map((_,i)=>a+i);}
function v35CheckedLessons(){return [...document.querySelectorAll('.v35-jpvi-check:checked')].map(x=>+x.value).filter(Boolean);}
function v35SetLessons(ids){const set=new Set(ids);document.querySelectorAll('.v35-jpvi-check').forEach(x=>x.checked=set.has(+x.value));v35UpdateSummary();}
function v35UpdateSummary(){const ids=v35CheckedLessons();const count=ids.reduce((s,id)=>s+v35Lesson(id).vocab.length,0);const box=document.getElementById('v35-jpvi-summary');if(box)box.innerHTML=`Đã chọn <b>${ids.length}</b> bài • <b>${count}</b> từ / biểu đạt`;}
function openV35JpViFlash(preset='default'){
  try{setNav('practice')}catch{}
  const root=document.getElementById('app');if(!root)return;
  root.innerHTML=`<div class="breadcrumb"><button onclick="goHome()">Trang chủ</button> › <button onclick="openPractice()">Luyện tập</button> › Flash Nhật → Việt</div>
  <section class="v35-jpvi-hero"><div><span class="v35-kicker">🇯🇵 → 🇻🇳 • RANDOM FLASHCARD • BÀI 1–50</span><h1>Flash Nhật → Việt</h1><p>Mặt trước chỉ hiện <b>Kana tiếng Nhật</b>. Tự nhớ nghĩa rồi bấm lật để xem <b>nghĩa tiếng Việt</b>. Kanji chỉ hiện phụ ở mặt đáp án.</p></div><div class="v35-demo"><small>MẶT TRƯỚC</small><b>かります</b><span>↓ lật thẻ</span><strong>mượn, vay</strong></div></section>
  <section class="panel v35-jpvi-setup"><div class="section-title"><div><h2>Chọn Bài 1–50</h2><p>Chọn một hoặc nhiều bài để trộn Flashcard.</p></div><div class="v35-quick"><button class="secondary-btn" onclick="v35SetLessons(v35Range(1,5))">1–5</button><button class="secondary-btn" onclick="v35SetLessons(v35Range(1,10))">1–10</button><button class="secondary-btn" onclick="v35SetLessons(v35Range(1,25))">N5 • 1–25</button><button class="secondary-btn" onclick="v35SetLessons(v35Range(26,50))">N4 • 26–50</button><button class="primary-btn" onclick="v35SetLessons(v35Range(1,50))">Tất cả 1–50</button><button class="ghost-btn" onclick="v35SetLessons([])">Bỏ chọn</button></div></div>
  <div class="v35-lesson-groups"><div class="v35-group"><h3>N5 • Bài 1–25</h3><div class="v35-lesson-selector">${LESSONS.map(l=>`<label><input class="v35-jpvi-check" type="checkbox" value="${l.id}" onchange="v35UpdateSummary()"><span><b>${l.id}</b><small>${l.vocab.length} từ</small></span></label>`).join('')}</div></div><div class="v35-group"><h3>N4 • Bài 26–50</h3><div class="v35-lesson-selector">${N4_MINNA_LESSONS.map(l=>`<label><input class="v35-jpvi-check" type="checkbox" value="${l.id}" onchange="v35UpdateSummary()"><span><b>${l.id}</b><small>${l.vocab.length} từ</small></span></label>`).join('')}</div></div></div>
  <div id="v35-jpvi-summary" class="v35-summary"></div><div class="v35-options"><label><b>Số thẻ</b><select id="v35-jpvi-count"><option value="10">10 thẻ</option><option value="20" selected>20 thẻ</option><option value="50">50 thẻ</option><option value="100">100 thẻ</option><option value="all">Tất cả từ đã chọn</option></select></label><button class="primary-btn" onclick="v35StartJpVi()">Bắt đầu Nhật → Việt →</button></div><div id="v35-jpvi-area"></div></section>`;
  if(preset==='n5')v35SetLessons(v35Range(1,25));else if(preset==='n4')v35SetLessons(v35Range(26,50));else if(preset==='all')v35SetLessons(v35Range(1,50));else v35SetLessons(v35Range(1,5));
}
function v35BuildCards(ids,count){let pool=[];ids.forEach(id=>{const l=v35Lesson(id);l.vocab.forEach((v,index)=>pool.push({lesson:id,level:l.level,index,kana:v35Kana(v),jp:String(v.jp||v.kana||'').trim(),vi:String(v.vi||'').trim(),reading:String(v.reading||'').trim()}));});pool=shuffle(pool);if(count!=='all')pool=pool.slice(0,Math.min(+count,pool.length));return pool;}
function v35StartJpVi(){const ids=v35CheckedLessons(),summary=document.getElementById('v35-jpvi-summary');if(!ids.length){if(summary)summary.innerHTML='<span class="danger">Hãy chọn ít nhất 1 bài.</span>';return;}const count=document.getElementById('v35-jpvi-count')?.value||'20';v35JpViState={ids,count,cards:v35BuildCards(ids,count),index:0,revealed:false,remembered:0,forgot:0,forgotten:[],cardStartedAt:Date.now()};v35RenderCard();}
function v35RenderCard(){const s=v35JpViState,area=document.getElementById('v35-jpvi-area');if(!s||!area)return;if(s.index>=s.cards.length)return v35RenderResult();const c=s.cards[s.index],pct=Math.round(s.index/s.cards.length*100);s.revealed=false;s.cardStartedAt=Date.now();area.innerHTML=`<div class="v35-session"><div class="v35-top"><div><span>${c.level} • BÀI ${c.lesson}</span><b>🇯🇵 NHẬT → 🇻🇳 VIỆT</b></div><strong>${s.index+1}/${s.cards.length}</strong></div><div class="progressbar v35-progress"><span style="width:${pct}%"></span></div><button class="v35-card" onclick="v35Reveal()"><small>MẶT TRƯỚC • TIẾNG NHẬT</small><strong>${escapeHtml(c.kana)}</strong><span id="v35-hint">Tự nhớ nghĩa tiếng Việt • bấm để lật</span><div id="v35-answer"></div></button><div id="v35-rate"></div><div class="v35-bottom"><button class="ghost-btn" onclick="v35ShuffleCurrent()">↻ Xáo lại bộ này</button></div></div>`;}
function v35Reveal(){const s=v35JpViState;if(!s||s.revealed)return;s.revealed=true;const c=s.cards[s.index],hasKanji=c.jp&&c.jp!==c.kana;const hint=document.getElementById('v35-hint');if(hint)hint.textContent='ĐÁP ÁN';const ans=document.getElementById('v35-answer');if(ans)ans.innerHTML=`<div class="v35-meaning"><small>NGHĨA TIẾNG VIỆT</small><b>${escapeHtml(c.vi)}</b></div>${hasKanji?`<div class="v35-kanji"><small>KANJI</small><strong>${escapeHtml(c.jp)}</strong></div>`:''}${c.reading?`<span class="v35-reading">${escapeHtml(c.reading)}</span>`:''}`;document.getElementById('v35-rate').innerHTML=`<div class="v35-rate-row"><button class="memory-btn again" onclick="v35Rate(false)">Quên</button><button class="memory-btn good" onclick="v35Rate(true)">Nhớ</button></div>`;}
function v35Rate(ok){const s=v35JpViState;if(!s||!s.revealed)return;const c=s.cards[s.index];if(ok)s.remembered++;else{s.forgot++;s.forgotten.push(c);}recordRecallEvent({itemKey:recallKey(['v35-jp-vi',c.lesson,c.index]),domain:'vocab',skill:'flash-jp-vi',lesson:c.lesson,itemLabel:c.kana,target:c.vi,prompt:`${c.kana} → nghĩa tiếng Việt?`,selected:ok?'remembered':'forgot',correctAnswer:c.vi,correct:ok,rating:ok?'good':'again',responseMs:Date.now()-(s.cardStartedAt||Date.now()),source:`V35 • Nhật → Việt • ${c.level} Bài ${c.lesson}`,qType:'v35-jp-to-vi-flash',extra:{level:c.level,vocabIndex:c.index}});s.index++;v35RenderCard();}
function v35RetryForgotten(){const s=v35JpViState;if(!s?.forgotten?.length)return;s.cards=shuffle([...s.forgotten]);s.index=0;s.revealed=false;s.remembered=0;s.forgot=0;s.forgotten=[];v35RenderCard();}
function v35NewRandomSet(){const s=v35JpViState;if(!s)return;s.cards=v35BuildCards(s.ids,s.count);s.index=0;s.revealed=false;s.remembered=0;s.forgot=0;s.forgotten=[];v35RenderCard();}
function v35ShuffleCurrent(){const s=v35JpViState;if(!s)return;s.cards=shuffle([...s.cards]);s.index=0;s.revealed=false;s.remembered=0;s.forgot=0;s.forgotten=[];v35RenderCard();}
function v35RenderResult(){const s=v35JpViState,area=document.getElementById('v35-jpvi-area');if(!s||!area)return;const total=s.cards.length,pct=total?Math.round(s.remembered/total*100):0;area.innerHTML=`<div class="v35-result"><span>🇯🇵 → 🇻🇳 FLASH COMPLETE</span><h2>${s.remembered}/${total}</h2><p>Nhớ <b>${pct}%</b> • Quên ${s.forgot} thẻ.</p><div>${s.forgotten.length?`<button class="primary-btn" onclick="v35RetryForgotten()">Ôn lại ${s.forgotten.length} thẻ quên →</button>`:''}<button class="secondary-btn" onclick="v35NewRandomSet()">Random bộ mới ↻</button><button class="ghost-btn" onclick="openV35JpViFlash()">Chọn lại bài</button></div></div>`;}
const _v35RecallSkillLabel=recallSkillLabel;
recallSkillLabel=function(skill){if(skill==='flash-jp-vi')return 'Flash: Nhật → Việt';return _v35RecallSkillLabel(skill);};
setTimeout(v35InjectPracticeCard,0);
